### ISSUE TITLE
Messages icon doesn't show up

### ISSUE THREAD

**Issue by abxyap** [Traurige/Liddell#5]
**Describe the bug:**
Only messages icon doesn't show up.

**Steps to reproduce the behavior:**

**Crash log:**
Upload your log file to pastebin and paste the link here.

**System information:**
- iOS version: 15.4.1
- Device: 13 Pro max
- Jailbreak: Fugu15

**Comment by Traurige** [comment]
Could you add me on Discord to do some investigation with me? @abxyap

**Comment by abxyap** [comment]
Thanks very  much.The issue solved.
