### ISSUE TITLE
Test Banner button isn’t working and App Icons aren’t showing.

### ISSUE THREAD

**Issue by ACHIYA96** [Traurige/Liddell#6]
**Describe the bug:**
1. Test Banner button in preferences doesn’t work. Simply it’s not responding.
2. App Icons in the notification banners, doesn’t show up. (Tested with Messages, Whatsapp, Telegram)
Edit: Gmail, Shortcuts app icons are visible. I think the issue is with the “Messaging” apps.

**Steps to reproduce the behavior:**
Go to “Settings- Liddell” and Touch on “Test Banner” button.

**Crash log:**
No crashes

**System information:**
- iOS version: 15.2
- Device: iPhone SE (2020) A13
- Jailbreak: Dopamine

**Comment by Traurige** [comment]
Related: #5

**Comment by Traurige** [comment]
Again something I can’t reproduce. Could you add me on Discord for further investigation?

**Comment by Traurige** [comment]
#8

**Comment by ACHIYA96** [comment]
Thank you very much for the fix 🙌
