### ISSUE TITLE
Icon feature improvement

### ISSUE THREAD

**Issue by pasabk** [Traurige/Liddell#9]
**Describe the requested feature:**

 Kindly improve the tweak such that is is able to display icon as per the application settings. Like on Whatsapp, I need to see the sender profile picture when I set it using Watusi. On default system notifications and velvet2 it works correctly but on Liddell it always shows the app icon as the icon on notification. If possible also allow to see the senders name (whatsapp) on Liddell works with system notifications and velvet2.

Otherwise thanks for such a great tweak

**System information:**
- iOS version: 15.3.1
- Device: Iphone 11 Pro Max
- Jailbreak: Dopamine

**Comment by Traurige** [comment]
This isn't going to be added.
